import media
import fresh_tomatoes

toy_story = media.Movie("Toy Story", "A group of toys come to life and try to find their way back home before their owner, Andy, moves away.", "Tom Hanks, Tim Allen, Don Rickles", "8.3/10", "http://upload.wikimedia.org/wikipedia/en/1/13/Toy_Story.jpg", "https://www.youtube.com/watch?v=vwyZH85NQC4")
avatar = media.Movie("Avatar", "The human race trys to retrieve resources from an alien planet while the native inhabitants protect their land.", "Sam Worthington, Zoe Saldana, Sigourney Weaver", "7.9/10", "http://upload.wikimedia.org/wikipedia/id/b/b0/Avatar-Teaser-Poster.jpg", "https://www.youtube.com/watch?v=5PSNL1qE6VY")
pirates_caribbean = media.Movie("Pirates of the Caribbean: At World's End", "The pirates band together in an attempt to protect their way of life from those that wish them eradicated.", "Johnny Depp, Orlando Bloom, Keira Knightley", "7.1/10", "https://upload.wikimedia.org/wikipedia/en/5/5a/Pirates_AWE_Poster.jpg", "https://www.youtube.com/watch?v=HKSZtp_OGHY")
ratatouille = media.Movie("Ratatouille", "An untalented chef gets help from a rat who knows how to cook.", "Brad Garrett, Lou Romano, Patton Oswalt", "8.0/10", "http://images.fanpop.com/images/image_uploads/Ratatouille-poster-ratatouille-324474_1215_1800.jpg", "https://www.youtube.com/watch?v=c3sBBRxDAqk")
transformers = media.Movie("Transformers: Age of Extinction", "The creators of the transformers return in full force to retrieve their inventions.", "Mark Wahlberg, Nicola Peltz, Jack Reynor", "5.8/10", "https://upload.wikimedia.org/wikipedia/en/9/94/Transformers_Age_of_Extinction_Poster.jpeg", "https://www.youtube.com/watch?v=pbI980iUb78")
hunger_games = media.Movie("Hunger Games", "A 16-year-old girl is forced to fight to the death in an arena agaisnt other districts.", "Jennifer Lawrence, Josh Hutcherson, Liam Hemsworth", "7.3/10", "http://www.hungergamesdwtc.net/wp-content/uploads/2014/02/The-Hunger-Games-Poster.jpg", "https://www.youtube.com/watch?v=mfmrPu43DF8")
first_dates = media.Movie("50 First Dates", "A man works hard everyday to remind a girl with short-term memory loss about the love he has for her.", "Adam Sandler, Drew Barrymore, Rob Schneider", "6.8/10", "http://ia.media-imdb.com/images/M/MV5BMjAwMzc4MDgxNF5BMl5BanBnXkFtZTYwNjUwMzE3._V1_SX640_SY720_.jpg", "https://www.youtube.com/watch?v=ErjP5xMTc8I")
lord_of_the_rings = media.Movie("Lord of the Rings: Return of the King", "The ring bearer and his team take their final stand to save their land from evil.", "Elijah Wood, Viggo Mortensen, Ian McKellen", "8.9/10", "http://ia.media-imdb.com/images/M/MV5BMjE4MjA1NTAyMV5BMl5BanBnXkFtZTcwNzM1NDQyMQ@@._V1_SX640_SY720_.jpg", "https://www.youtube.com/watch?v=r5X-hFf6Bwo")
star_trek = media.Movie("Star Trek", "The Star Ship Enterprise trys to stop a future race that came back in time to destroy the Federation.", "Chris Pine, Zachary Quinto, Simon Pegg", "8.0/10", "http://static.rogerebert.com/uploads/movie/movie_poster/star-trek-2009/large_lkQgAaI9s2j2Lhlkie8I9RcWYEX.jpg", "https://www.youtube.com/watch?v=SyJszxnJydA")
land_before_time = media.Movie("The Land Before Time", "The tale of 5 baby dinosaurs making their journey to find the Great Valley.", "Pat Hingle, Gabriel Damon, Judith Barsi", "7.3/10", "http://ia.media-imdb.com/images/M/MV5BOTkyNjQ0MDA1OV5BMl5BanBnXkFtZTcwMDkyMTYyMQ@@._V1_SX640_SY720_.jpg", "https://www.youtube.com/watch?v=lpnwK2NGxIo")


movies = [toy_story, avatar, pirates_caribbean, ratatouille, transformers, hunger_games, first_dates, star_trek, land_before_time]
fresh_tomatoes.open_movies_page(movies)
